TOPLEVEL_LANG = verilog
SIM = icarus

VERILOG_SOURCES = ../../../RTL/Register_File.v
TOPLEVEL = Register_File
COCOTB_TEST_MODULES = test_register_file

include $(shell cocotb-config --makefiles)/Makefile.sim